version: "2"

services:
  postgres:
    restart: always
    image: postgres:10.1
    environment:
      - POSTGRES_USER=whisp
      - POSTGRES_PASSWORD=whisp
      - POSTGRES_DB=whisp_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
    networks:
      - dev_machine_net

  whisp:
    build: .
    image: firestata/whisp:v0.1
    depends_on:
      - "postgres"
    links:
      - "postgres"
    networks:
      - dev_machine_net
    ports:
      - 4000:4000
networks:
  dev_machine_net:
    driver: bridge
